# Generated by Django 5.2.1 on 2025-05-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ODBCConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dsn",
                    models.CharField(
                        max_length=255, verbose_name="Nome da Fonte de Dados (DSN)"
                    ),
                ),
                ("uid", models.CharField(max_length=255, verbose_name="Usuário (UID)")),
                ("pwd", models.CharField(max_length=255, verbose_name="Senha (PWD)")),
                (
                    "driver",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Driver ODBC"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuração ODBC",
                "verbose_name_plural": "Configurações ODBC",
                "ordering": ["-updated_at"],
            },
        ),
    ]
