# Generated by Django 5.2.1 on 2025-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpresaSincronizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codi_emp",
                    models.IntegerField(
                        db_index=True,
                        help_text="Identificador único da empresa no sistema ODBC (ex: geempre.codi_emp)",
                        unique=True,
                        verbose_name="Código da Empresa no ODBC",
                    ),
                ),
                (
                    "habilitada_sincronizacao",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a sincronização desta empresa com o Fiscaut está ativa.",
                        verbose_name="Sincronização Habilitada",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Empresa para Sincronização",
                "verbose_name_plural": "Empresas para Sincronização",
                "ordering": ["codi_emp"],
            },
        ),
    ]
