# Generated by Django 5.2.1 on 2025-05-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0002_empresasincronizacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscautApiConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        help_text="A URL base para a API Fiscaut. Ex: https://api.fiscaut.com.br/v1",
                        max_length=255,
                        verbose_name="URL Base da API Fiscaut",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="A chave de API para autenticação com a API Fiscaut.",
                        max_length=255,
                        verbose_name="Chave da API Fiscaut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuração da API Fiscaut",
                "verbose_name_plural": "Configurações da API Fiscaut",
            },
        ),
    ]
