# Generated by Django 5.2.1 on 2025-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0003_fiscautapiconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiscautapiconfig",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="fiscautapiconfig",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="fiscautapiconfig",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="fiscautapiconfig",
            name="api_key",
            field=models.CharField(
                help_text="A chave secreta para autenticação com a API Fiscaut.",
                max_length=255,
                verbose_name="Chave da API Fiscaut",
            ),
        ),
        migrations.AlterField(
            model_name="fiscautapiconfig",
            name="api_url",
            field=models.URLField(
                help_text="A URL base para a API Fiscaut. Ex: https://api.fiscaut.com.br/v1",
                max_length=255,
                verbose_name="URL da API Fiscaut",
            ),
        ),
    ]
