# Generated by Django 5.2.1 on 2025-05-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0004_remove_fiscautapiconfig_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FornecedorStatusSincronizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codi_emp_odbc",
                    models.IntegerField(verbose_name="Código da Empresa ODBC"),
                ),
                (
                    "codi_for_odbc",
                    models.CharField(
                        max_length=50, verbose_name="Código do Fornecedor ODBC"
                    ),
                ),
                (
                    "status_sincronizacao",
                    models.CharField(
                        choices=[
                            ("NAO_SINCRONIZADO", "Não Sincronizado"),
                            ("SINCRONIZADO", "Sincronizado"),
                            ("ERRO", "Erro na Sincronização"),
                        ],
                        default="NAO_SINCRONIZADO",
                        max_length=20,
                        verbose_name="Status da Sincronização",
                    ),
                ),
                (
                    "ultima_tentativa_sinc",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Última Tentativa de Sincronização",
                    ),
                ),
                (
                    "detalhes_ultima_resposta",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Detalhes da Última Resposta da API",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status de Sincronização de Fornecedor",
                "verbose_name_plural": "Status de Sincronização de Fornecedores",
                "ordering": ["codi_emp_odbc", "codi_for_odbc"],
                "unique_together": {("codi_emp_odbc", "codi_for_odbc")},
            },
        ),
    ]
