# Generated by Django 5.2.1 on 2025-05-29 19:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0005_fornecedorstatussincronizacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data e hora do log."
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        help_text="Nível do log.",
                        max_length=10,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Módulo onde o log foi gerado.", max_length=255
                    ),
                ),
                (
                    "func_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome da função onde o log foi gerado.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "line_no",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número da linha onde o log foi gerado.",
                        null=True,
                    ),
                ),
                ("message", models.TextField(help_text="Mensagem do log.")),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="Traceback do erro, se aplicável.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log da Aplicação",
                "verbose_name_plural": "Logs da Aplicação",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="fiscautapiconfig",
            options={
                "ordering": ["-is_active", "-updated_at"],
                "verbose_name": "Configuração da API Fiscaut",
                "verbose_name_plural": "Configurações da API Fiscaut",
            },
        ),
        migrations.AddField(
            model_name="empresasincronizacao",
            name="ultima_sincronizacao",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora da última sincronização bem-sucedida.",
                null=True,
                verbose_name="Última Sincronização",
            ),
        ),
        migrations.AddField(
            model_name="fiscautapiconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fiscautapiconfig",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Marcar como configuração ativa."
            ),
        ),
        migrations.AddField(
            model_name="fiscautapiconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fornecedorstatussincronizacao",
            name="fiscaut_id",
            field=models.CharField(
                blank=True,
                help_text="ID do fornecedor na API Fiscaut após sincronização bem-sucedida.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fiscautapiconfig",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="fornecedorstatussincronizacao",
            name="status_sincronizacao",
            field=models.CharField(
                choices=[
                    ("NAO_SINCRONIZADO", "Não Sincronizado"),
                    ("SINCRONIZADO", "Sincronizado"),
                    ("ERRO", "Erro na Sincronização"),
                    ("EM_ANDAMENTO", "Sincronização em Andamento"),
                ],
                default="NAO_SINCRONIZADO",
                max_length=20,
                verbose_name="Status da Sincronização",
            ),
        ),
        migrations.AlterField(
            model_name="odbcconfiguration",
            name="driver",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Driver ODBC"
            ),
        ),
        migrations.AlterField(
            model_name="odbcconfiguration",
            name="dsn",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Nome da Fonte de Dados (DSN)"
            ),
        ),
        migrations.AddIndex(
            model_name="fornecedorstatussincronizacao",
            index=models.Index(
                fields=["codi_emp_odbc", "codi_for_odbc"],
                name="sync_fornec_codi_em_d33408_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fornecedorstatussincronizacao",
            index=models.Index(
                fields=["status_sincronizacao"], name="sync_fornec_status__eb4521_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationlog",
            index=models.Index(fields=["level"], name="sync_applic_level_31b4c3_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationlog",
            index=models.Index(fields=["module"], name="sync_applic_module_4278f3_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationlog",
            index=models.Index(
                fields=["timestamp"], name="sync_applic_timesta_2c11a5_idx"
            ),
        ),
    ]
